---
- name: install some package
  yum: name={{ item }} state=latest
  with_items: 
    - zlib-devel
    - bzip2-devel
    - openssl-devel
    - splite-devel
    - readline-devel
    - libffi-devel

- name: transfer python to remote 
  template: src=Python-3.7.4 dest=/opt/

- name: configure python and install
  shell: cd /opt/Python-3.7.4; ./configure --enable-shared; make && make install

- name: write the python export file
  template: src=python3_lib.sh dest=/etc/profile.d/

- name: transfer lib file to remote
  template: src=python3.conf dest=/etc/ld.so.conf.d/

- name: source and ldconfig files
  shell: source /etc/profile; ldconfig

- name: create the virtual env
  shell: python3 -m venv /myvenv

- name: install uwsgi
  shell: cd /myvenv/bin/; source activate ; pip3 install uwsgi;deactivate

- name: create  uwsgi link
  file: src=/myvenv/bin/uwsgi dest=/usr/bin/uwsgi state=link
 
