---
- name: transfer nginx.repo to remote machine
  template: 
    src: nginx.repo
    dest: /etc/yum.repos.d/nginx.repo

- name: install nginx server
  yum: 
    name: nginx
    state: latest

- name: transfer nginxconf to remote machine
  template:
    src: nginxconf.j2
    dest: /etc/nginx/conf.d/default.conf
  notify: start nginx service
