---
- name: transfer nginx source package
  template: src=nginx-1.16.1 dest=/opt/

- name: transfer create user shell script
  template: src=useradd.sh dest=/opt/

- name: execute shell script
  shell: bash /opt/useradd.sh

- name: install some package
  yum: name={{ item }} state=latest
  with_items:
    - openssl-devel
    - pcre-devel
    - zlib-devel
    - gcc
    - gcc++

- name: configure and install nginx
  shell: cd /opt/nginx-1.16.1; ./configure --prefix=/usr/local/nginx --user=nginx --group=nginx --with-http_ssl_module --with-http_stub_status_module; make && make install
  notify: start nginx service
