---
- name: transfer mysql.repo to remote machine
  template: 
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: install mysql service 
  yum: 
    name: ['MySQL-python','mysql-community-server']
    state: latest

- name: create relay_bin file
  shell: touch /var/log/relay-bin.index

- name: tansfer my.cnf to remote service
  template:
    src: mycnf.j2
    dest: /etc/my.cnf
  notify: 
    - start mysql service

- name: transfer initPsd.sh to remote machine
  template: 
    src: initpsd.j2
    dest: /opt/initpsd.sh

- name: execute initpsd.sh
  shell: bash /opt/initpsd.sh

- name: configure the replication to the slave
  mysql_replication: 
    mode: changemaster
    login_user: root
    login_password: "{{ mysql_root_password}}"
    master_host: "{{ mysql_master_host }}"
    master_user: "{{ mysql_user_name }}"
    master_password: "{{ mysql_user_password }}"
    master_auto_position: yes

- name: start slave
  mysql_replication:
    mode: startslave 
